# Site Settings
name: e-lab innovations
title: e-lab innovations | Learn | Innovate | Share
description: e-lab innovations blog
tags:
  - e-lab
  - innovations
  - blog
  - e-labinnovations
  - Mohammed Ashad
email: elabinnovations@gmail.com
disqus_username: e-labinnovations
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml


# Social Media Settings
# Remove the item if you don't need it
github_username: e-labinnovations
facebook_username: elabin
twitter_username:
instagram_username: mohammed_ashad_23
linkedin_username: mohammed-ashad-525134176
medium_username: mohammedashad23


# Posts Settings
show_time_bar: true
show_modal_on_exit: false
show_modal_on_finish_post: false
two_columns_layout: true


# Advanced Settings
baseurl: '' # the subpath of your site, e.g. /blog
url: '' # the base hostname & protocol for your site
google_analytics: 'UA-145449081-1'
language: 'en'
categories_folder: category
sent_message_url: '/contact/message-sent/'


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
collections:
  authors:
    output: true
paginate_path: '/page/:num/'
show_get_theme_btn: true
use_logo: true

# Content paginator
paginate_content:
  enabled: true
  debug: false
  collections:
    - posts
  auto: false
  separator: '--page-break--'
  permalink: '/:num/'
  seo_canonical: true
  properties:
    part:
      is_generated: true
    last:
      is_generated: true
    single:
      is_generated: true

# SASS
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-paginate-content

# Exclude my node related stuff
exclude:
  [
    'package.json',
    'package-lock.json',
    'src',
    'node_modules',
    'initpost.sh',
    'Gemfile',
    'Gemfile.lock',
    'gulpfile.js',
    'README.md',
  ]

# Theme
version: v3.0.2
