
title: Mohammed Ashad
url: 'https://e-labInnovations.github.io'
baseurl: '/e-labInnovations.github.io' #change it according to your repository name



# Profile information
yourname: Mohammed Ashad  ## put your name
title: 'Electronics student with vs code editor'  ## your title
location: Kerala, India


## Social Profiles
facebook: http://www.facebook.com/mohammed.ashad23  ## your facebook account url
twitter: http://www.twitter.com  ## your twitter account url
linkedin: https://www.linkedin.com/in/mohammed-ashad-525134176  ## your linkedin account url
github: https://github.com/e-labInnovations ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
